psql postgres -c "DROP SCHEMA public CASCADE;"
psql postgres -U init -c "DROP DATABASE IF EXISTS student;"
psql postgres -U init -c "DROP FUNCTION IF EXISTS support;"
psql postgres -U init -c "DROP FUNCTION IF EXISTS protest;"
psql postgres -U init -c "DROP FUNCTION IF EXISTS leader;"
psql postgres -U init -c "DROP USER IF EXISTS app;"
psql postgres -U init -c "CREATE DATABASE student;"
psql postgres -c "SELECT pg_catalog.set_config('search_path', 'public', false);"
psql postgres -c "CREATE SCHEMA public;"
