psql postgres -c "DROP SCHEMA public CASCADE;"
psql postgres -c "DROP DATABASE IF EXISTS student;"
psql postgres -c "DROP USER IF EXISTS app;"
psql postgres -c "CREATE DATABASE student;"
psql postgres -c "CREATE SCHEMA public;"
